name: Deploy to Cloud Run

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/986352892503/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deployer@cloudrun-demo-485707.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cloudrun-demo \
            --source . \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
